import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='mx-auto h-screen flex flex-col bg-[url(/background.JPG)] bg-cover'>
      <div className='bg-rose-700 flex flex-col items-center text-center justify-center w-full h-full saturate-[.25] opacity-70 text-white'>
        <h1 className='font-serif tracking-wide'>
          John D&apos;cruz
        </h1>
        <p className='text-xl'>
          Multimedia Production | Software Development
        </p>
      </div>
      </main>
    </div>
  )
}